name: Stage

permissions:
  actions: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches: [develop]
    paths-ignore:
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup mise
      uses: jdx/mise-action@v2

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile

    - name: Build Application
      run: pnpm build-app

    - name: Archive Package
      run: pnpm pack

    - name: Archive Desktop Extension
      run: pnpm build-dxt

    - name: Upload Package
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: "*.tgz"
        if-no-files-found: error

    - name: Upload Desktop Extension
      uses: actions/upload-artifact@v4
      with:
        name: desktop-extension
        path: "*.dxt"
        if-no-files-found: error

  docker-develop:
    needs: build
    runs-on: ubuntu-latest
    env:
      DOCKER_NAMESPACE: onlyoffice
      DOCKER_REPOSITORY: docspace-mcp
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: Publish Image
      uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        labels: develop
        tags: docker.io/${{env.DOCKER_NAMESPACE}}/4testing-${{env.DOCKER_REPOSITORY}}:${{ github.sha }}

