name: Stage

permissions:
  actions: write
  contents: read

on:
  workflow_dispatch:

jobs:
  stage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup mise
      uses: jdx/mise-action@v2

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile

    - name: Build Application
      run: pnpm build-app

    - name: Archive Package
      run: pnpm pack

    - name: Archive Desktop Extension
      run: pnpm build-dxt

    - name: Upload Package
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: "*.tgz"
        if-no-files-found: error

    - name: Upload Desktop Extension
      uses: actions/upload-artifact@v4
      with:
        name: desktop-extension
        path: "*.dxt"
        if-no-files-found: error
